# Generated by Django 5.0.1 on 2026-01-29 22:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Course code (e.g., QIT-101)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Course name', max_length=200)),
                ('semester', models.CharField(help_text='Semester (e.g., Winter 2025/2026)', max_length=50)),
                ('year', models.IntegerField(default=1, help_text="Year of study (1 or 2 for Master's)")),
                ('semester_type', models.CharField(choices=[('winter', 'Winter Semester'), ('summer', 'Summer Semester')], default='winter', max_length=10)),
                ('ects', models.IntegerField(help_text='ECTS credits', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('course_type', models.CharField(choices=[('mandatory', 'Mandatory'), ('elective', 'Elective'), ('optional', 'Optional')], default='mandatory', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Course description and syllabus')),
                ('instructor', models.CharField(blank=True, help_text='Instructor name(s)', max_length=200)),
                ('hours_per_week', models.IntegerField(default=0, help_text='Contact hours per week')),
                ('schedule', models.TextField(blank=True, help_text="Class schedule (e.g., 'Mon 10:00-12:00, Wed 14:00-16:00')")),
                ('syllabus_url', models.URLField(blank=True, help_text='Link to course syllabus PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['program', 'year', 'semester_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the program (e.g., Quantum Information Technology)', max_length=200)),
                ('university', models.CharField(help_text='University name (e.g., University of Gdańsk)', max_length=200)),
                ('faculty', models.CharField(blank=True, help_text='Faculty or department name', max_length=200)),
                ('degree_type', models.CharField(choices=[('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('postdoc', 'Postdoctoral')], default='master', max_length=20)),
                ('total_ects_required', models.IntegerField(default=120, help_text='Total ECTS credits required for graduation')),
                ('is_active', models.BooleanField(default=True, help_text='Is this program currently active?')),
                ('color', models.CharField(default='#3B82F6', help_text='Color code for visual identification (hex format, e.g., #3B82F6)', max_length=7)),
                ('description', models.TextField(blank=True, help_text='Additional information about the program')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Assignment title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the assignment')),
                ('assignment_type', models.CharField(choices=[('homework', 'Homework'), ('project', 'Project'), ('exam', 'Exam'), ('quiz', 'Quiz'), ('presentation', 'Presentation'), ('lab', 'Lab Work'), ('other', 'Other')], default='homework', max_length=20)),
                ('due_date', models.DateTimeField(help_text='Deadline for submission')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('max_points', models.FloatField(default=100.0, help_text='Maximum points possible', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_completed', models.BooleanField(default=False, help_text='Has this assignment been completed?')),
                ('completed_date', models.DateTimeField(blank=True, help_text='When was this assignment completed?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course this assignment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.course')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='planned', max_length=20)),
                ('enrolled_date', models.DateField(default=django.utils.timezone.now, help_text='Date of enrollment')),
                ('is_passed', models.BooleanField(default=False, help_text='Did the student pass this course?')),
                ('notes', models.TextField(blank=True, help_text='Personal notes about the course')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course being taken', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.course')),
                ('user', models.ForeignKey(help_text='Student enrolled in the course', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-enrolled_date'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(help_text='Grade on Polish scale (2.0 - 5.0)', validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(5.0)])),
                ('points', models.FloatField(blank=True, help_text='Points earned', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_points', models.FloatField(blank=True, help_text='Maximum points possible', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight', models.FloatField(default=1.0, help_text='Weight in final grade calculation (0.0 - 1.0)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date grade was received')),
                ('comment', models.TextField(blank=True, help_text='Additional comments or feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, help_text='Related assignment (optional for final grades)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='core.assignment')),
                ('enrollment', models.ForeignKey(help_text='Which enrollment does this grade belong to?', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.enrollment')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(help_text='Which program does this course belong to?', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.program'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('program', 'code')},
        ),
    ]
